version: "3.8"

services:
  products-api:
    build: .
    container_name: products-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=products-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=products_db
    depends_on:
      - products-db

  products-db:
    image: postgres:16
    container_name: products-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products_db
    ports:
      - "5432:5432"
    volumes:
      - products_data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql

volumes:
  products_data:
